# Obsidian Curator Configuration
# This file contains the default configuration for the curation process

# AI Model Configuration
ai_model: "gpt-oss:20b"  # Ollama model to use for analysis
reasoning_level: "low"   # AI reasoning level: low, medium, high
max_tokens: 2000         # Maximum tokens for AI analysis

# Quality Thresholds (0.0 - 1.0)
quality_threshold: 0.7   # Minimum overall quality score for curation
relevance_threshold: 0.6 # Minimum relevance score for curation

# Target Themes (leave empty for all themes)
target_themes:
  - infrastructure
  - construction
  - governance
  - sustainability
  - economics

# Processing Options
preserve_metadata: true  # Whether to preserve original note metadata
clean_html: true        # Whether to clean HTML content from web clippings
remove_duplicates: true # Whether to remove duplicate content

# Sample Size (for testing - leave null for all notes)
sample_size: null       # Number of notes to process (random sample)
