# Obsidian Curator Configuration
# Optimized thresholds for better content capture (August 2024)

# AI Model Configuration
ai_model: "gpt-oss:20b"
models:
  content_curation: "phi3:mini"
  quality_analysis: "llama3.1:8b"
  theme_classification: "llama3.1:8b"
  structure_analysis: "phi3:mini"
  fallback: "gpt-oss:20b"

# Reasoning Level
reasoning_level: "low"

# Quality Thresholds (0.0 - 1.0) - Optimized for better content capture
quality_threshold: 0.65  # Minimum overall quality score for curation (lowered for broader capture)
relevance_threshold: 0.65  # Minimum relevance score for curation (maintained for precision)
analytical_depth_threshold: 0.65  # Minimum analytical depth for publication-ready content
professional_writing_threshold: 0.65  # Minimum professional writing score for curation (lowered from 0.70)

# Content Processing
min_content_length: 300   # Minimum content length (characters) for useful notes (lowered for valuable short notes)
max_tokens: 2000          # Maximum tokens for AI analysis

# Theme Configuration
target_themes: []  # Empty list means all themes are considered
theme_similarity_threshold: 0.3

# Processing Options
preserve_metadata: true
clean_html: true
remove_duplicates: true

# Sample Size (for testing)
sample_size: 20
